site_name: Kanso Documentation
site_description: Personal finance tracking with calm and clarity
site_url: https://dstmrk.github.io/kanso/
repo_url: https://github.com/dstmrk/kanso
repo_name: dstmrk/kanso
edit_uri: edit/main/docs/

theme:
  name: material
  logo: static/logo_small.png
  favicon: static/favicon.ico
  palette:
    # Light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: Roboto Mono
  features:
    - navigation.instant      # Fast page loading
    - navigation.tracking     # URL updates with scroll
    - navigation.tabs         # Top-level tabs
    - navigation.sections     # Collapsible sections
    - navigation.top          # Back to top button
    - search.suggest          # Search suggestions
    - search.highlight        # Highlight search terms
    - content.code.copy       # Copy code button
    - content.action.edit     # Edit page link
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Google Sheets Setup: google-sheets-setup.md
      - Configuration: configuration.md
  - Technical:
      - Architecture: architecture.md
      - API Reference: api-reference.md
  - Contributing: contributing.md

markdown_extensions:
  # Python Markdown extensions
  - abbr                      # Abbreviations
  - admonition                # Note, warning boxes
  - attr_list                 # Add HTML attributes
  - def_list                  # Definition lists
  - footnotes                 # Footnotes
  - md_in_html                # Markdown in HTML
  - toc:
      permalink: true         # Add permalink to headings
      toc_depth: 3

  # PyMdown Extensions
  - pymdownx.arithmatex:      # Math formulas
      generic: true
  - pymdownx.betterem:        # Better emphasis
      smart_enable: all
  - pymdownx.caret            # Superscript
  - pymdownx.mark             # Highlighting
  - pymdownx.tilde            # Strikethrough
  - pymdownx.details          # Collapsible blocks
  - pymdownx.emoji:           # Emoji support
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:       # Code highlighting
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite     # Inline code highlighting
  - pymdownx.keys             # Keyboard keys
  - pymdownx.smartsymbols     # Smart symbols
  - pymdownx.superfences:     # Nested code blocks
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:          # Content tabs
      alternate_style: true
  - pymdownx.tasklist:        # Task lists
      custom_checkbox: true

plugins:
  - search:                   # Search plugin
      lang: en

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dstmrk/kanso
      name: GitHub Repository
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: Thanks for your feedback!

copyright: Copyright &copy; 2024 Kanso Contributors
